/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guillermoespinal_lab8;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
         dba.conectar();
         llamada = new hilollamada();//(lb_s,lb_m,lb_h);
         llamada = new hilollamada(lb_s, lb_m, lb_h);
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_llamada = new javax.swing.JDialog();
        lb_nombre = new javax.swing.JLabel();
        bt_fin = new javax.swing.JButton();
        lb_s = new javax.swing.JLabel();
        lb_m = new javax.swing.JLabel();
        lb_h = new javax.swing.JLabel();
        lb_s1 = new javax.swing.JLabel();
        lb_s2 = new javax.swing.JLabel();
        jd_mensaje = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_mensaje = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        cb_mensajiar = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_correo = new javax.swing.JTextField();
        tf_dirreccion = new javax.swing.JTextField();
        sp_edad = new javax.swing.JSpinner();
        bt_agregar = new javax.swing.JButton();
        tf_numero = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        cb_contactos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tf_nombre1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_correo1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sp_edad1 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        tf_dirreccion1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_numero1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_lista = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        cb_eliminar = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_specs = new javax.swing.JTextArea();
        bt_eliminar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        cb_llamar = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_mensajes = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        lb_nombre.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        bt_fin.setText("Finalizar llamada");
        bt_fin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_finMouseClicked(evt);
            }
        });

        lb_s.setText("00");

        lb_m.setText("00");

        lb_h.setText("00");

        lb_s1.setText(":");

        lb_s2.setText(":");

        javax.swing.GroupLayout jd_llamadaLayout = new javax.swing.GroupLayout(jd_llamada.getContentPane());
        jd_llamada.getContentPane().setLayout(jd_llamadaLayout);
        jd_llamadaLayout.setHorizontalGroup(
            jd_llamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_llamadaLayout.createSequentialGroup()
                .addGroup(jd_llamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_llamadaLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lb_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_llamadaLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(lb_h)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_s2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_m)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_s1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_s))
                    .addGroup(jd_llamadaLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(bt_fin)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jd_llamadaLayout.setVerticalGroup(
            jd_llamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_llamadaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lb_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addGroup(jd_llamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_s)
                    .addComponent(lb_h)
                    .addComponent(lb_m)
                    .addComponent(lb_s1)
                    .addComponent(lb_s2))
                .addGap(53, 53, 53)
                .addComponent(bt_fin)
                .addGap(58, 58, 58))
        );

        ta_mensaje.setColumns(20);
        ta_mensaje.setRows(5);
        jScrollPane4.setViewportView(ta_mensaje);

        jButton4.setText("Enviar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_mensajeLayout = new javax.swing.GroupLayout(jd_mensaje.getContentPane());
        jd_mensaje.getContentPane().setLayout(jd_mensajeLayout);
        jd_mensajeLayout.setHorizontalGroup(
            jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mensajeLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mensajeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mensajeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_mensajiar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jd_mensajeLayout.setVerticalGroup(
            jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mensajeLayout.createSequentialGroup()
                .addGroup(jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mensajeLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(cb_mensajiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mensajeLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(99, 99, 99))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Correo electronico :");

        jLabel3.setText("Edad:");

        jLabel4.setText("Direccion :");

        jLabel5.setText("Numero :");

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 200, 1));

        bt_agregar.setText("Agregar");
        bt_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarMouseClicked(evt);
            }
        });

        try {
            tf_numero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_agregar)
                .addGap(76, 76, 76))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_dirreccion, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sp_edad))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_dirreccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(bt_agregar)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Contactos", jPanel1);

        cb_contactos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_contactosItemStateChanged(evt);
            }
        });

        jLabel6.setText("Nombre:");

        jLabel7.setText("Correo electronico :");

        jLabel8.setText("Edad:");

        sp_edad1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 200, 1));

        jLabel9.setText("Direccion :");

        jLabel10.setText("Numero :");

        try {
            tf_numero1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton1.setText("Modificar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_dirreccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sp_edad1))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_correo1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(312, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cb_contactos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(105, 105, 105))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(cb_contactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_correo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sp_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_dirreccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(104, 104, 104))
        );

        jTabbedPane1.addTab("Modificar algun contacto", jPanel2);

        jt_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Numero", "Correo", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_lista);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contactos", jPanel3);

        cb_eliminar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_eliminarItemStateChanged(evt);
            }
        });

        ta_specs.setColumns(20);
        ta_specs.setRows(5);
        jScrollPane2.setViewportView(ta_specs);

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(bt_eliminar)
                        .addGap(120, 120, 120))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(cb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(bt_eliminar)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Contactos", jPanel4);

        jButton2.setText("LLamar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(cb_llamar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jButton2)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(cb_llamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(169, 169, 169))
        );

        jTabbedPane1.addTab("Llamar ", jPanel5);

        table_mensajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Aquien", "Fecha", "Mensaje"
            }
        ));
        jScrollPane3.setViewportView(table_mensajes);

        jButton3.setText("Enviar Nuevo Mensaje");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(jButton3)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mensajiar", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarMouseClicked
        //agregar
//        Dba db = new Dba("./base1.mdb");
//        db.conectar();
//        try {
//            int c;
//            String n;
//            c = Integer.parseInt(JOptionPane.showInputDialog("Codigo"));
//            n = JOptionPane.showInputDialog("Nombre");
//            db.query.execute("INSERT INTO alumnos"
//                    + " (cuenta,nombre)"
//                    + " VALUES ('" + c + "', '" + n + "')");
//            db.commit();
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }
//        db.desconectar();
        try {
            String nombre = tf_nombre.getText();
            String correo = tf_correo.getText();
            int edad = (int) sp_edad.getValue();
            String direccion= tf_dirreccion.getText();
            String numero = tf_numero.getText();
            dba.query.execute("INSERT INTO contactos(Nombre,Edad,Numero,Correo,Direccion) "
                    + "VALUES ('"+nombre+"','"+(Integer.toString(edad))+"','"+numero+"','"+correo+"','"+direccion+"')");
            dba.commit();
            dba.desconectar();
            JOptionPane.showMessageDialog(this, "HAS AGREGADO UN NUEVO CONTACTO");
            tf_correo.setText("");
            tf_dirreccion.setText("");
            tf_nombre.setText("");
            tf_numero.setText(null);
            sp_edad.setValue(1);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "No se pudo guardar el contacto");
            //meanwhile
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_bt_agregarMouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
    cargarContactos();
        System.out.println("Lo hago perro");
    
        jt_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Numero", "Correo", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        //System.out.println(""+contactos.size());
        for (int i = 0; i < contactos.size(); i++) {
            Object[] newrow = {
                contactos.get(i).getNombre(),
                contactos.get(i).getEdad(),
                contactos.get(i).getNumero(),
                contactos.get(i).getCorreo(),
                contactos.get(i).getDirrecion()
            };
            DefaultTableModel modelo = (DefaultTableModel)jt_lista.getModel();
            modelo.addRow(newrow);
            jt_lista.setModel(modelo);
        }
      try {
            cb_contactos.setModel(new DefaultComboBoxModel<>());
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_contactos.getModel();
            for (int i = 0; i < contactos.size(); i++) {
                modelo.addElement(contactos.get(i));
            }
      }catch(Exception e ){
          
      }
      try {
            cb_eliminar.setModel(new DefaultComboBoxModel<>());
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_eliminar.getModel();
            for (int i = 0; i < contactos.size(); i++) {
                modelo.addElement(contactos.get(i));
            }
      }catch(Exception e ){
          
      }
      try {
            cb_llamar.setModel(new DefaultComboBoxModel<>());
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_llamar.getModel();
            for (int i = 0; i < contactos.size(); i++) {
                modelo.addElement(contactos.get(i));
            }
      }catch(Exception e ){
          
      }
      /*table_mensajes.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
      
      },
      new String [] {
      "Nombre", "Aquien", "Fecha", "Mensaje"
      }
      ) {
      boolean[] canEdit = new boolean [] {
      false, false, false, false
      };
      
      public boolean isCellEditable(int rowIndex, int columnIndex) {
      return canEdit [columnIndex];
      }
      });*/
        try {
                cb_mensajiar.setModel(new DefaultComboBoxModel<>());
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_mensajiar.getModel();
                for (int i = 0; i < contactos.size(); i++) {
                    modelo.addElement(contactos.get(i));
                }
            } catch (Exception e) {
            }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void cb_contactosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_contactosItemStateChanged
        // YA VEREMOS QUE PEDOOOO
        Contacto contact = (Contacto)cb_contactos.getSelectedItem();
        tf_nombre1.setText(contact.getNombre());
        tf_correo1.setText(contact.getCorreo());
        tf_numero1.setText(contact.getNumero());
        sp_edad1.setValue(contact.getEdad());
        tf_dirreccion1.setText(contact.getDirrecion());
        
    }//GEN-LAST:event_cb_contactosItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Contacto contact = (Contacto)cb_contactos.getSelectedItem();
        
        String nombre = tf_nombre1.getText();
            String correo = tf_correo1.getText();
            int edad = (int) sp_edad1.getValue();
            String direccion= tf_dirreccion1.getText();
            String numero = tf_numero1.getText();
            //modificar
//        Dba db = new Dba("./base1.mdb");
//        db.conectar();
//        try {
//            db.query.execute("update alumnos set direccion='Residencial' where cuenta=123");
//            db.commit();//nota = nota+5
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }
//        db.desconectar();
        dba.conectar();
        try {
            /*   dba.query.execute("update contactos "
            + "set Nombre='"+nombre+"',set Edad='"+Integer.toString(edad)+"',set Numero= '"+numero+"',set Correo='"+correo+"',set Direccion='"+direccion+"' where Numero='"+numero+"'");*/
            dba.query.execute("update contactos set Nombre ='"+nombre+"' where Numero ='"+contact.getNumero()+"'");
            dba.query.execute("update contactos set Edad ='"+Integer.toString(edad)+"' where Numero ='"+contact.getNumero()+"'");
            dba.query.execute("update contactos set Correo ='"+correo+"' where Numero ='"+contact.getNumero()+"'");
            dba.query.execute("update contactos set Direccion ='"+direccion+"' where Numero ='"+contact.getNumero()+"'");
            dba.query.execute("update contactos set Numero ='"+numero+"' where Numero ='"+contact.getNumero()+"'");
           // dba.query.execute("update contactos set Nombre ='"+nombre+"' where Numero ='"+contact.getNumero()+"'");
            dba.commit();
            JOptionPane.showMessageDialog(this, "Se a modificado el contacto");
              tf_correo.setText("");
            tf_dirreccion.setText("");
            tf_nombre.setText("");
            tf_numero.setText(null);
            sp_edad.setValue(1);
             try {
            cb_contactos.setModel(new DefaultComboBoxModel<>());
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_contactos.getModel();
            for (int i = 0; i < contactos.size(); i++) {
                modelo.addElement(contactos.get(i));
            }
      }catch(Exception e ){
          
      }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Creo que me mame");
            e.printStackTrace();
        }
        dba.desconectar();
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void cb_eliminarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_eliminarItemStateChanged
       Contacto contact = (Contacto)cb_eliminar.getSelectedItem();
        ta_specs.setText(contact.getNombre()+"\n"
                +contact.getNumero()+"\n"
                +contact.getEdad()+"\n"
                +contact.getCorreo()+"\n"
                +contact.getDirrecion());
        //eliminar
//        Dba db = new Dba("./base1.mdb");
//        db.conectar();
//        try {
//            db.query.execute("delete from alumnos where cuenta=5000");
//            db.commit();
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }
//        db.desconectar();
/* dba.conectar();
try {
dba.query.execute("delete from contactos where Numero="+contact.getNumero()+"");
dba.commit();
} catch (Exception e) {
}*/

                
    }//GEN-LAST:event_cb_eliminarItemStateChanged

    private void bt_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminarMouseClicked
       Contacto contact = (Contacto)cb_eliminar.getSelectedItem();
        dba.conectar();
        try {
            dba.query.execute("delete from contactos where Numero='"+contact.getNumero()+"'");
            dba.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }
        dba.desconectar();
        JOptionPane.showMessageDialog(this, "Se a eliminado el contacto");
        
        try {
            cargarContactos();
            
            try {
                cb_eliminar.setModel(new DefaultComboBoxModel<>());
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_eliminar.getModel();
                for (int i = 0; i < contactos.size(); i++) {
                    modelo.addElement(contactos.get(i));
                }
            } catch (Exception e) {
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bt_eliminarMouseClicked

    private void bt_finMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_finMouseClicked
       JOptionPane.showMessageDialog(this, "Llamada finalizada");
       llamada.setVive(false);
       
    }//GEN-LAST:event_bt_finMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        cargarllamada();
        jd_llamada.setModal(true);
        jd_llamada.pack();
        jd_llamada.setVisible(true);
        jd_llamada.setEnabled(true);
      
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        jd_mensaje.setModal(true);
        jd_mensaje.pack();
        jd_mensaje.setVisible(true);
        jd_mensaje.setEnabled(true);
        
            
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        try {
            mensajiar= (Contacto)cb_mensajiar.getSelectedItem();
            String mensaje = ta_mensaje.getText();
            Date date = new Date();
            SimpleDateFormat sp = new SimpleDateFormat("dd/MM/yyyy");
            
            String fecha = sp.format(date);
            /* dba.query.execute("INSERT INTO contactos(Nombre,Edad,Numero,Correo,Direccion) "
            + "VALUES ('"+nombre+"','"+(Integer.toString(edad))+"','"+numero+"','"+correo+"','"+direccion+"')");
            dba.commit();
            dba.desconectar();*/
            dba.conectar();
            dba.query.execute("INSERT INTO mensajes(Nombre,Aquien,Fecha,Mensaje) "
                    + "VALUES('"+you+"','"+mensajiar.getNombre()+"','"+fecha+"','"+mensaje+"')");
            dba.commit();
            dba.desconectar();
              JOptionPane.showMessageDialog(this,"Se a enviado el mensaje");
              DefaultTableModel modelo = (DefaultTableModel)table_mensajes.getModel();
              Object[] row = {you,mensajiar.getNombre(),fecha,mensaje};
              modelo.addRow(row);
        } catch (SQLException ex) {
            //Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
          JOptionPane.showMessageDialog(this, "me mame");
          ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public void cargarContactos(){
        contactos= new ArrayList<>();
     
        dba.conectar();
        try {
            dba.query.execute("select Nombre,Edad,Numero,Correo,Direccion from contactos");
            ResultSet rs = dba.query.getResultSet();
            while (rs.next()) {
                //boolean next = rs.next();
                //System.out.println(rs.getString(1));
                contactos.add(new Contacto(rs.getString(1), Integer.parseInt(rs.getString(2)), rs.getString(3), rs.getString(4), rs.getString(5)));
                
            }
            
        } catch (NumberFormatException | SQLException e) {
            e.printStackTrace();
        }
        dba.desconectar();
        //ResultSet
    }
    public void cargarllamada(){
         try {
             
            llamar = (Contacto) cb_llamar.getSelectedItem();
            lb_nombre.setText(llamar.getNombre());
            
            //hilollamada llamada = new hilollamada(lb_s,lb_m,lb_h);
            llamada.start();
        } catch (Exception e) {
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_fin;
    private javax.swing.JComboBox<String> cb_contactos;
    private javax.swing.JComboBox<String> cb_eliminar;
    private javax.swing.JComboBox<String> cb_llamar;
    private javax.swing.JComboBox<String> cb_mensajiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jd_llamada;
    private javax.swing.JDialog jd_mensaje;
    private javax.swing.JTable jt_lista;
    private javax.swing.JLabel lb_h;
    private javax.swing.JLabel lb_m;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_s;
    private javax.swing.JLabel lb_s1;
    private javax.swing.JLabel lb_s2;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_edad1;
    private javax.swing.JTextArea ta_mensaje;
    private javax.swing.JTextArea ta_specs;
    private javax.swing.JTable table_mensajes;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_correo1;
    private javax.swing.JTextField tf_dirreccion;
    private javax.swing.JTextField tf_dirreccion1;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JFormattedTextField tf_numero;
    private javax.swing.JFormattedTextField tf_numero1;
    // End of variables declaration//GEN-END:variables
ArrayList<Contacto> contactos = new ArrayList<>();
String you = "Tu";
String numero= "3163-6701";
String correotu = "guiller.gaes@gmail.com";
int edad = 18;
  Dba dba = new Dba("./contactos.accdb");
  Contacto llamar = new Contacto();
   hilollamada llamada = new hilollamada();//(lb_s,lb_m,lb_h);
   Contacto mensajiar ;



}
